#!/bin/bash
# ==========================================
# Color
# download menu
cd /root
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/install
chmod +x /root/install
cd
mkdir /root/bin
chmod +x /root/bin
cd /root/bin
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-host
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-on
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/addssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-ssh-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/addtj
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-trojan-gfw
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-trojan-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/addvl
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-vless-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/addvm
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/add-vmess-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/backup
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/cek-service
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/cek-ssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/cek-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/cek-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/cek-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/cert
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/clear-log
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/delexp
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/delssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/del-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/del-trojan-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/del-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/del-vless-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/del-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/del-vmess-trial
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/gboy
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-ip-ssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-ip-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-ip-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-ip-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-quota-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-quota-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/limit-quota-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/list-ssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/list-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/list-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/list-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/log-ssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/log-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/log-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/log-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/loop
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/matikan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/menu-add-on
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/menu-ssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/menu-system
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/menu-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/menu-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/menu-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/mesinssh
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-trojan-grpc
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-trojan-tcp
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-trojan-ws
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-vless-grpc
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-vless-ws
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-vmess-grpc
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-vmess-ws
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-vmess-ws-orbit
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/quota-vmess-ws-orbit1
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/renewsshprem
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/renew-trojan-prem
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/renew-vless-prem
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/renew-vmess-prem
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/switch-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/trial-trojan
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/trial-vless
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/trial-vmess
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/unban-akun
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/user
wget https://raw.githubusercontent.com/shahihku/penyalahan/main/bin/xp
cd
